### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mygod** [zehuanli/Google-Voice-Mark-Read#5]
2024.10.21.691108989

**Comment by zehuanli** [comment]
Any logs please? I have the exact same version and it's working.

**Comment by Mygod** [comment]
```
[ 2024-11-14T21:35:26.740    10365: 27683: 27683 E/LSPlant         ] Hook Fails: _ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE
[ 2024-11-14T21:35:26.741    10365: 27683: 27683 E/LSPlant         ] Failed to init jit code cache
[ 2024-11-14T21:35:26.741    10365: 27683: 27683 E/LSPosed         ] Failed to init lsplant
[ 2024-11-14T21:35:26.749    10365: 27683: 27683 I/LSPosed         ] Loading xposed for com.google.android.apps.googlevoice/10365
[ 2024-11-14T21:35:26.773    10365: 27683: 27683 I/LSPosed-Bridge  ] Loading legacy module com.upbad.apps.vogo from /data/app/~~jG247hMZfbdPWG_FNNJz9g==/com.upbad.apps.vogo-MaX2avozD47czNDNXODPiA==/base.apk
[ 2024-11-14T21:35:26.774    10365: 27683: 27683 I/LSPosed-Bridge  ]   Loading class com.upbad.apps.vogo.Main
[ 2024-11-14T21:35:26.826    10365: 27683: 27683 I/LSPosed-Bridge  ] [VOGO] NotificationActions hook() started
[ 2024-11-14T21:35:26.827    10365: 27683: 27683 I/LSPosed-Bridge  ] [VOGO] NotificationActions hook() finished
[ 2024-11-14T21:35:27.530    10365: 27683: 27742 E/LSPosed         ] error when hooking LoadedApk#createClassLoader: pkg=com.google.android.apps.googlevoice, prc=com.google.android.apps.googlevoice
java.lang.NoSuchFieldError: android.app.LoadedApk#mIncludeCode
	at zjExWM.CVFEwJMh.eb.rvt.XposedHelpers.lambda$findField$1(Unknown Source:6)
	at zjExWM.CVFEwJMh.eb.rvt.XposedHelpers.j(Unknown Source:0)
	at zjExWM.CVFEwJMh.eb.rvt.b.get(Unknown Source:9)
	at java.util.Optional.orElseThrow(Optional.java:403)
	at zjExWM.CVFEwJMh.eb.rvt.XposedHelpers.findField(Unknown Source:25)
	at zjExWM.CVFEwJMh.eb.rvt.XposedHelpers.getBooleanField(Unknown Source:4)
	at h0.a(Unknown Source:133)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.-$$Nest$mcreateOrUpdateClassLoaderLocked(Unknown Source:0)
	at android.app.LoadedApk$SplitDependencyLoaderImpl.constructSplit(LoadedApk.java:723)
	at android.content.pm.split.SplitDependencyLoader.loadDependenciesForSplit(SplitDependencyLoader.java:70)
	at android.app.LoadedApk$SplitDependencyLoaderImpl.ensureSplitLoaded(LoadedApk.java:759)
	at android.app.LoadedApk$SplitDependencyLoaderImpl.getSplitPathsForSplit(LoadedApk.java:771)
	at android.app.LoadedApk.getSplitPaths(LoadedApk.java:791)
	at android.app.ContextImpl.createResources(ContextImpl.java:2648)
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2757)
	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2730)
	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:1092)
	at com.google.android.gms.dynamiteloader.DynamiteLoaderV2.loadModule2NoCrashUtils(:com.google.android.gms.dynamite_dynamiteloader@244337029@24.43.37 (190400-0):44)
	at m.cd.a(:com.google.android.gms.dynamite_dynamiteloader@244337029@24.43.37 (190400-0):73)
	at m.j.onTransact(:com.google.android.gms.dynamite_dynamiteloader@244337029@24.43.37 (190400-0):21)
	at android.os.Binder.transact(Binder.java:1196)
	at ciw.b(PG:8)
	at gwg.b(PG:211)
	at hah.b(PG:45)
	at com.google.android.gms.net.PlayServicesCronetProvider.tryToInstallCronetProvider(PG:3)
	at com.google.android.gms.net.PlayServicesCronetProvider.isEnabled(PG:1)
	at org.chromium.net.CronetEngine$Builder.getEnabledCronetProviders(PG:25)
	at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(PG:14)
	at org.chromium.net.CronetEngine$Builder.<init>(PG:1)
	at org.chromium.net.ExperimentalCronetEngine$Builder.<init>(PG:1)
	at den.get(PG:15)
	at j$.util.Optional.orElseGet(SourceFile:6)
	at nhy.m(PG:122)
	at etv.b(PG:1234)
	at oyz.e(PG:12)
	at oyz.b(PG:7)
	at nbo.b(PG:195)
	at oyz.e(PG:12)
	at oyz.b(PG:7)
	at lae.a(PG:31)
	at los.a(PG:224)
	at mrn.a(PG:3)
	at mqt.run(PG:19)
	at mrp.run(PG:5)
	at hfk.run(PG:3)
	at mlg.run(PG:50)
	at hde.run(PG:632)
	at java.lang.Thread.run(Thread.java:1012)
	at hgw.run(PG:64)
```

**Comment by zehuanli** [comment]
This is interesting because on my phone I can see the same error in the LSPosed verbose log. However, the module still works for me (for both the version you provided and a newer version 2024.11.03.694499019). @Mygod are you able to see the "mark as read" button added in the message notifications?

**Comment by Mygod** [comment]
No, that is missing. That exception also looks unrelated. For what it's worth, I'm running Android 14 (OnePlus OxygenOS).

**Comment by Mygod** [comment]
Oh sorry is this for messages only? I thought there is an option for voicemails too.

**Comment by zehuanli** [comment]
Ah, yes, this is for message notifications only. Voicemails are untouched.
